CREATE DATABASE IF NOT EXISTS MTBD;

USE MTBD;

CREATE TABLE IF NOT EXISTS UF (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(75) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS CIDADES (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    ID_UF INTEGER NOT NULL,
    NOME VARCHAR(75),
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (ID_UF) REFERENCES UF (CODIGO)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    ID_UF INTEGER NOT NULL,
    ID_CIDADE INTEGER NOT NULL,
    NOME VARCHAR(150) NOT NULL,
	PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(150) NOT NULL,
    PRECO_VENDA FLOAT NOT NULL,
    PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    ID_ENTIDADE INTEGER NOT NULL,
    DATA_EMISSAO DATETIME NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY (ID_ENTIDADE) REFERENCES CLIENTES (CODIGO)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_PEDIDO (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    ID_PEDIDO INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QTDE FLOAT NOT NULL, 
    VLR_UNITARIO FLOAT NOT NULL,
    VLR_TOTAL FLOAT NOT NULL,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (CODIGO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (CODIGO)
);


