object frmFundo: TfrmFundo
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 125
  BorderStyle = bsNone
  Caption = 'frmFundo'
  ClientHeight = 338
  ClientWidth = 868
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Visible = True
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
end
